version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    restart: always
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data: